### ISSUE TITLE
php-mode defines require-final-newline

### ISSUE THREAD

**Issue by gjm** [glasserc/ethan-wspace#33]
Hi.

When i open a buffer in `php-mode` i get the warning:

    Warning (:warning): You have
    `require-final-newline' turned on.  ethan-wspace supersedes
    `require-final-newline', and so `require-final-newline' will be
    turned off.  If you turned on `require-final-newline' in your
    customizations, you can disable this warning by removing these
    customizations.  Otherwise, please file a bug report, as some
    other code has turned on `require-final-newline'.

As far as i can tell, looking at `php-mode.el`, that variable is set when defining the various syntax styles supported by the mode (i'm using psr2, btw).

I've tried setting the variable to `nil` after loading `ethan-wspace` and in `php-mode-hook` all with no results...  How can i get rid of this warning?

Thanks in advance.

**Comment by glasserc** [comment]
Hi, thanks for your interest. Which `php-mode` are you using? I'm guessing https://github.com/ejmr/php-mode/blob/master/php-mode.el ?

In my opinion, `php-mode` should not unconditionally set `require-final-newline`. Indeed, if `php-mode` inherits from `prog-mode`, it probably shouldn't touch `require-final-newline` at all, because `prog-mode` does the correct thing (set `require-final-newline` to `mode-require-final-newline`). However, there may be some subtlety that I am not aware of so if you tell me which `php-mode` to contact, I will open an issue to discuss it with the maintainer.

**Comment by glasserc** [comment]
I have opened https://github.com/ejmr/php-mode/issues/424 to discuss the issue with the `php-mode` folks.

**Comment by gjm** [comment]
Thanks. I've subscribed to the issue to follow the discussion.


Atentamente,

Gonçalo Marrafa

**Comment by glasserc** [comment]
The upstream issue is now closed so I think we can close this too. Please tell me if your issue persists!
